### ISSUE TITLE
Null pointer exception when using a visual studio solution

### ISSUE THREAD

**Issue by ochafik** [ochafik/JNAerator#11]
_From @ochafik on September 1, 2011 18:47_

<b>What steps will reproduce the problem?</b>
1. I try to generate interfaces for a whole solution
2. I run "java -jar jnaerator-0.9.5.jar sundials.sln"
3. And it results in an exception

<b>What is the expected output? What do you see instead?</b>
They output is:
Dec 29, 2010 6:21:11 PM com.ochafik.admin.visualstudio.VisualStudioUtils getProp
INFO: [environment] ProgramFiles(x86)=C:\Program Files (x86)
Dec 29, 2010 6:21:11 PM com.ochafik.admin.visualstudio.VisualStudioUtils getProp
INFO: [environment] VISUAL_STUDIO_HOME=C:\Program Files (x86)\Microsoft Visual Studio 9.0
Dec 29, 2010 6:21:11 PM com.ochafik.admin.visualstudio.VisualStudioUtils getProp
INFO: [environment] ProgramFiles(x86)=C:\Program Files (x86)
Dec 29, 2010 6:21:11 PM com.ochafik.admin.visualstudio.VisualStudioUtils getProp
INFO: [environment] WINDOWS_SDK_HOME=C:\Program Files (x86)\Microsoft SDKs\Windows\v6.0A
Dec 29, 2010 6:21:11 PM com.ochafik.admin.visualstudio.VisualStudioUtils getProp
INFO: [environment] VISUAL_STUDIO_INCLUDES=C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\include;C:\Program Files (x86)\Microsoft SDKs\Windows\v6.0A\Include
Error parsing arguments :
sundials.sln
Finished with errors.
java.lang.NullPointerException
	at com.ochafik.lang.jnaerator.JNAeratorConfigUtils.readProjectConfig(JNAeratorConfigUtils.java:390)
	at com.ochafik.lang.jnaerator.JNAerator$1.parsedFile(JNAerator.java:565)
	at com.ochafik.lang.jnaerator.JNAerator$1.parsed(JNAerator.java:400)
	at com.ochafik.lang.jnaerator.JNAeratorCommandLineArgs$ArgsParser.parse(JNAeratorCommandLineArgs.java:89)
	at com.ochafik.lang.jnaerator.JNAerator.main(JNAerator.java:290)
	at com.ochafik.lang.jnaerator.JNAerator.main(JNAerator.java:171)

<b>What version of the product are you using? On what operating system?</b>

<b>Is the problem still present in the latest SVN version ? (you can easily</b>
<b>build from sources with these instructions :</b>
<b>http://code.google.com/p/javacl/wiki/Build)</b>

<b>Please provide any additional information below.</b>
I tried to generate a java interface for the Sundials (https://computation.llnl.gov/casc/sundials/main.html) library which is written in C. Following their installation instructions and using CMake, I created a visual studio solution. Then I compiled it for Windows with Visual Studio 2010. I then tried to use the aforementioned command to generate the java interface but it failed with the given exception. I can also provide the complete solution with the code and built dlls if needed (somewhere around 100mb I guess).

Google Code Info:
Issue #: 77
Author: darko.ce...@gmail.com
Created On: 2010-12-29T17:35:16.000Z
Closed On: 

_Copied from original issue: ochafik/nativelibs4java#154_

**Comment by ochafik** [comment]
Hello,

JNAerator was never debugged with VS 2010 solutions, so there might be some work to do...
Will investigate ASAP.

Cheers
--
zOlive

Google Code Info:
Author: olivier.chafik
Created On: 2011-02-18T17:19:40.000Z

**Comment by ochafik** [comment]
VisualStudioUtils.java does not support Microsoft Visual Studio 10.0. Now, it only try to setup the environment from the following path:
    VISUAL_STUDIO_INCLUDES=C:\Program Files\Microsoft Visual Studio 9.0\VC\include;C:\Program Files\Microsoft SDKs\Windows\v6.0A\Include

After upgrading from Visual Studio 10.0, all the files under the Include folder are moved to the new version place.  The path should be:

    VISUAL_STUDIO_INCLUDES=C:\Program Files\Microsoft Visual Studio 10.0\VC\include;C:\Program Files\Microsoft SDKs\Windows\v7.0A\Include





Google Code Info:
Author: LiuYJe...@gmail.com
Created On: 2011-08-24T20:09:06.000Z

**Comment by ochafik** [comment]
_From @JennyLiu on June 12, 2012 13:50_

Have you upgraded to Visual Studio 10.0? which version includes this fix?
