### ISSUE TITLE
Partial specialization file name

### ISSUE THREAD

**Issue by ochafik** [ochafik/JNAerator#13]
_From @ochafik on September 1, 2011 18:47_

<b>What steps will reproduce the problem?</b>
1. Create a new file test.h containing

template <class T>
struct my_template<int> { 
    // A partial specialization
};

2. Run jnaerator
java -jar jnaerator-0.9.7-SNAPSHOT-shaded.jar -library Test test.h -o . -v -noJar -noComp

<b>What is the expected output? What do you see instead?</b>

It fails to create the correct java file for the structure, because it tries to put angle brackets with the type in the filename.

Now parsing 1 text blocks
Normalizing parsed code...
Writing raw parsed sources to '_jnaerator.rawParsed.cpp'
Writing normalized parsed sources to '_jnaerator.normalizedParsed.cpp'
Generating libraries...
Struct with no field : my_template<int >
Generating my_template<int >.java
JNAeration failed !
java.io.FileNotFoundException: .\test\my_template<int >.java (The filename, directory name, or volume label syntax is incorrect)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.PrintWriter.<init>(Unknown Source)
        at com.ochafik.lang.jnaerator.JNAerator$3$1.<init>(JNAerator.java:795)
        at com.ochafik.lang.jnaerator.JNAerator$3.getClassSourceWriter(JNAerator.java:795)
        at com.ochafik.lang.jnaerator.JNAerator.getClassSourceWriter(JNAerator.java:745)
        at com.ochafik.lang.jnaerator.JNAerator$4.getClassSourceWriter(JNAerator.java:809)
        at com.ochafik.lang.jnaerator.DeclarationsConverter.outputConvertedStruct(DeclarationsConverter.java:1484)
        at com.ochafik.lang.jnaerator.DeclarationsConverter.convertStructs(DeclarationsConverter.java:1576)
        at com.ochafik.lang.jnaerator.JNAerator.fillLibraryMapping(JNAerator.java:1336)
        at com.ochafik.lang.jnaerator.JNAerator.generateJNALibraryFiles(JNAerator.java:1322)
        at com.ochafik.lang.jnaerator.JNAerator.generateLibraryFiles(JNAerator.java:1141)
        at com.ochafik.lang.jnaerator.JNAerator.jnaerationCore(JNAerator.java:1723)
        at com.ochafik.lang.jnaerator.JNAerator.jnaerate(JNAerator.java:831)
        at com.ochafik.lang.jnaerator.JNAerator$1.finished(JNAerator.java:721)
        at com.ochafik.lang.jnaerator.JNAeratorCommandLineArgs$ArgsParser.parse(JNAeratorCommandLineArgs.java:98)
        at com.ochafik.lang.jnaerator.JNAerator.main(JNAerator.java:292)
        at com.ochafik.lang.jnaerator.JNAerator.main(JNAerator.java:173)
Finished with errors.

<b>What version of the product are you using? On what operating system?</b>
Maven snapsot of 25/02/2011 (20110225010542)

<b>Is the problem still present in the latest SVN version ? (you can easily</b>
<b>build from sources with these instructions :</b>
<b>http://code.google.com/p/javacl/wiki/Build)</b>
Not tried yet, but tried with the last maven snapshot where the problem persists.

<b>Please provide any additional information below.</b>

Google Code Info:
Issue #: 83
Author: AODtoru...@gmail.com
Created On: 2011-02-25T13:58:32.000Z
Closed On: 

_Copied from original issue: ochafik/nativelibs4java#158_

**Comment by ochafik** [comment]
Hello,

Thanks for your report !
This definitely needs to be fixed (templates should be skipped for the JNA runtime output and handled properly for the BridJ runtime)

Cheers 
--
zOlive

Google Code Info:
Author: olivier.chafik
Created On: 2011-03-13T22:54:52.000Z
