### ISSUE TITLE
Unable to process Python 2.6: "Failed to match any alternative with token"

### ISSUE THREAD

**Issue by ochafik** [ochafik/JNAerator#22]
_From @yang on December 9, 2011 20:13_

I'm simply trying to process the [standard Python 2.6 headers on Ubuntu 10.04](http://packages.ubuntu.com/lucid/python2.6-dev). Transcript:

```
$ java -jar jnaerator-0.9.8-shaded.jar -library python26 /usr/include/python2.6/Python.h -o dst -v -noJar -noComp 2>&1 -I /usr/lib/gcc/x86_64-linux-gnu/4.4/include/
Auto-configuring parser...
Dec 9, 2011 12:04:45 PM com.ochafik.lang.jnaerator.JNAeratorConfigUtils getProp
INFO: [environment] JNAERATOR_INCLUDE_PATH=.:/usr/include:/usr/include/c++/4.4.3
Dec 9, 2011 12:04:45 PM com.ochafik.lang.jnaerator.JNAeratorConfigUtils getProp
INFO: [environment] JNAERATOR_FRAMEWORKS_PATH=/System/Library/Frameworks/CoreServices.framework/Versions/Current/Frameworks:/System/Library/Frameworks/ApplicationServices.framework/Versions/Current/Frameworks:/System/Library/Frameworks:/Library/Frameworks:/Local/Library/Frameworks/:/home/yang/Library/Frameworks
os.arch = amd64
Dec 9, 2011 12:04:45 PM com.ochafik.lang.jnaerator.JNAerator jnaerate
INFO: Include path : 
        /usr/lib/gcc/x86_64-linux-gnu/4.4/include
        .
        /usr/include
        /usr/include/c++/4.4.3
Parsing native headers...
/usr/include/bits/wchar.h:30:7: warning: Unexpected nonwhite token
/usr/include/bits/wchar.h:30:7: warning: Unexpected nonwhite token
/usr/include/bits/wchar.h:30:7: warning: Unexpected nonwhite token
/usr/include/bits/wchar.h:30:7: warning: Unexpected nonwhite token
Writing preprocessor output to '_jnaerator.preprocessed.c'
Writing preprocessor macros to '_jnaerator.macros.cpp'
line 0:-1 Failed to match any alternative with token [@-1,0:0='<no text>',<-1>,0:-1]
         File: null:0
        Input: 
         Rule: 1656:1: castExpr returns [Expression expr] : ( '(' tr= mutableTypeRef ')' (inner= castExpr | '(' expression ( ',' expression )+ ')' ) | e= unaryExpr );
        Stack: []

line 0:-1 Failed to match any alternative with token [@-1,0:0='<no text>',<-1>,0:-1]
         File: null:0
        Input: 
         Rule: 1656:1: castExpr returns [Expression expr] : ( '(' tr= mutableTypeRef ')' (inner= castExpr | '(' expression ( ',' expression )+ ')' ) | e= unaryExpr );
        Stack: []

line 0:-1 Failed to match any alternative with token [@-1,0:0='<no text>',<-1>,0:-1]
         File: null:0
        Input: 
         Rule: 1656:1: castExpr returns [Expression expr] : ( '(' tr= mutableTypeRef ')' (inner= castExpr | '(' expression ( ',' expression )+ ')' ) | e= unaryExpr );
        Stack: []

line 0:-1 Failed to match any alternative with token [@-1,0:0='<no text>',<-1>,0:-1]
         File: null:0
        Input: 
         Rule: 1656:1: castExpr returns [Expression expr] : ( '(' tr= mutableTypeRef ')' (inner= castExpr | '(' expression ( ',' expression )+ ')' ) | e= unaryExpr );
        Stack: []

line 0:-1 Failed to match any alternative with token [@-1,0:0='<no text>',<-1>,0:-1]
         File: null:0
        Input: 
         Rule: 1656:1: castExpr returns [Expression expr] : ( '(' tr= mutableTypeRef ')' (inner= castExpr | '(' expression ( ',' expression )+ ')' ) | e= unaryExpr );
        Stack: []

line 0:-1 Failed to match any alternative with token [@-1,0:0='<no text>',<-1>,0:-1]
         File: null:0
        Input: 
         Rule: 1656:1: castExpr returns [Expression expr] : ( '(' tr= mutableTypeRef ')' (inner= castExpr | '(' expression ( ',' expression )+ ')' ) | e= unaryExpr );



...



         Rule: 1656:1: castExpr returns [Expression expr] : ( '(' tr= mutableTypeRef ')' (inner= castExpr | '(' expression ( ',' expression )+ ')' ) | e= unaryExpr );
        Stack: []

line 0:-1 Failed to match any alternative with token [@-1,0:0='<no text>',<-1>,0:-1]
         File: null:0
        Input: 
         Rule: 1656:1: castExpr returns [Expression expr] : ( '(' tr= mutableTypeRef ')' (inner= castExpr | '(' expression ( ',' expression )+ ')' ) | e= unaryExpr );
        Stack: []

line 0:-1 Failed to match any alternative with token [@-1,0:0='<no text>',<-1>,0:-1]
         File: null:0
        Input: 
         Rule: 1656:1: castExpr returns [Expression expr] : ( '(' tr= mutableTypeRef ')' (inner= castExpr | '(' expression ( ',' expression )+ ')' ) | e= unaryExpr );
        Stack: []

line 1:0 Failed to match any alternative with token [@0,0:5='return',<55>,1:0]
         File: null:1
        Input: return   Py_INCREF ( Py_True )
         Rule: 1656:1: castExpr returns [Expression expr] : ( '(' tr= mutableTypeRef ')' (inner= castExpr | '(' expression ( ',' expression )+ ')' ) | e= unaryExpr );
        Stack: []

line 0:-1 Failed to match any alternative with token [@-1,0:0='<no text>',<-1>,0:-1]
         File: null:0
        Input: 
         Rule: 1656:1: castExpr returns [Expression expr] : ( '(' tr= mutableTypeRef ')' (inner= castExpr | '(' expression ( ',' expression )+ ')' ) | e= unaryExpr );
        Stack: []

line 1:18 extraneous input [@5,18:18='2',<4>,1:18] expecting ')'
line 0:-1 Failed to match any alternative with token [@-1,0:0='<no text>',<-1>,0:-1]
         File: null:0
        Input: 
         Rule: 1656:1: castExpr returns [Expression expr] : ( '(' tr= mutableTypeRef ')' (inner= castExpr | '(' expression ( ',' expression )+ ')' ) | e= unaryExpr );
        Stack: []

line 0:-1 Failed to match any alternative with token [@-1,0:0='<no text>',<-1>,0:-1]
         File: null:0
        Input: 
         Rule: 1656:1: castExpr returns [Expression expr] : ( '(' tr= mutableTypeRef ')' (inner= castExpr | '(' expression ( ',' expression )+ ')' ) | e= unaryExpr );
        Stack: []

line 1:0 Failed to match any alternative with token [@0,0:5='return',<55>,1:0]
         File: null:1
        Input: return   Py_INCREF ( Py_None )
         Rule: 1656:1: castExpr returns [Expression expr] : ( '(' tr= mutableTypeRef ')' (inner= castExpr | '(' expression ( ',' expression )+ ')' ) | e= unaryExpr );
        Stack: []

Now parsing 439 text blocks
Normalizing parsed code...
Writing raw parsed sources to '_jnaerator.rawParsed.cpp'
Writing normalized parsed sources to '_jnaerator.normalizedParsed.cpp'
Generating libraries...
Generating Python26Library.java
JNAeration completed !
/home/yang/tmp/dst

$ cat dst/python26/Python26Library.java
package python26;
import com.ochafik.lang.jnaerator.runtime.LibraryExtractor;
import com.ochafik.lang.jnaerator.runtime.MangledFunctionMapper;
import com.ochafik.lang.jnaerator.runtime.Mangling;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.Pointer;
/**
 * JNA Wrapper for library <b>python26</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface Python26Library extends Library {
        public static final String JNA_LIBRARY_NAME = LibraryExtractor.getLibraryPath("python26", true, python26.Python26Library.class);
        public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(python26.Python26Library.JNA_LIBRARY_NAME, com.ochafik.lang.jnaerator.runtime.MangledFunctionMapper.DEFAULT_OPTIONS);
        public static final Python26Library INSTANCE = (Python26Library)Native.loadLibrary(python26.Python26Library.JNA_LIBRARY_NAME, python26.Python26Library.class, com.ochafik.lang.jnaerator.runtime.MangledFunctionMapper.DEFAULT_OPTIONS);
        /// <i>native declaration : /usr/include/python2.6/Python.h</i>
        public static final int WITH_CYCLE_GC = (int)1;
        /// <i>native declaration : /usr/include/python2.6/Python.h</i>
        public static final int Py_file_input = (int)257;
        /// <i>native declaration : /usr/include/python2.6/Python.h</i>
        public static final int Py_single_input = (int)256;
        /// <i>native declaration : /usr/include/python2.6/Python.h</i>
        public static final int Py_eval_input = (int)258;
        /**
         * _Py_Mangle is defined in compile.c<br>
         * Original signature : <code>PyObject* _Py_Mangle(PyObject*, PyObject*)</code><br>
         * <i>native declaration : /usr/include/python2.6/Python.h:4</i>
         */
        @Mangling({"_Z10_Py_MangleP8PyObjectP8PyObject", "?_Py_Mangle@@YAPA8PyObjectPA8PyObjectPA8PyObject@Z"}) 
        Pointer _Py_Mangle(Pointer p, Pointer name);
        /// Undefined type
        public static interface PyObject {
                
        };
}
```

_Copied from original issue: ochafik/nativelibs4java#207_

**Comment by ochafik** [comment]
_From @twitwi on December 9, 2011 23:37_

Hi,

I worked on this some time ago and managed to obtain something.
I just checked and it is still working.
Here are some instructions:

  mkdir wrappython
  cd wrappython
  # install the dev files if not done with:
  aptitude install python2.6-dev
  # get a recent jnaerator if not done:
  wget http://angelcorp.be/maven2/com/jnaerator/jnaerator/0.9.9-SNAPSHOT/jnaerator-0.9.9-SNAPSHOT-shaded.jar
  ln -s /usr/include/python2.6 include26
 
Then fill your config.jnaerator file with:
-library python26
-package com.heeere.python26
-runtime BridJ
-noRuntime
-jar Python26.jar
-v
-I./include26
include26/Python.h
include26/pythonrun.h
include26/object.h
include26/moduleobject.h
include26/modsupport.h
include26/import.h
include26/abstract.h
include26/tupleobject.h

And finally build the jar:
java -jar jnaerator-0.9.9-SNAPSHOT-shaded.jar

I hope this helps,
Cheers,
Rémi

**Comment by ochafik** [comment]
_From @yang on December 16, 2011 3:26_

@twitwi (or anyone): jnaerator seems to be generating a Python26Library class for me containing `native` methods, instead of an interface extending the jna Library (as I'd expect after reading the jnaerator docs), when I use:

```
java -jar jnaerator-0.9.9-SNAPSHOT-shaded.jar -library python26 /usr/include/python2.6/{Python,pythonrun,object,moduleobject,modsupport,import,abstract,tupleobject}.h -o dst -I /usr/lib/gcc/x86_64-linux-gnu/4.4/include/
```

Any ideas why?

**Comment by ochafik** [comment]
_From @yang on December 16, 2011 3:32_

Also tried adding `-runtime BridJ` and then running:

```
$ scala -classpath dst/python26.jar -Djava.library.path=/usr/lib/
...
scala> System.loadLibrary("python2.6")

scala> python26.Python26Library.Py_Initialize()
java.lang.UnsatisfiedLinkError: python26.Python26Library.Py_Initialize()V
        at python26.Python26Library.Py_Initialize(Native Method)
        at .<init>(<console>:8)
        at .<clinit>(<console>)
        at .<init>(<console>:11)
        at .<clinit>(<console>)
        at $print(<console>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:616)
        at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:704)
        at scala.tools.nsc.interpreter.IMain$Request$$anonfun$14.apply(IMain.scala:920)
        at scala.tools.nsc.interpreter.Line$$anonfun$1.apply$mcV$sp(Line.scala:43)
        at scala.tools.nsc.io.package$$anon$2.run(package.scala:25)
        at java.lang.Thread.run(Thread.java:636)
```

**Comment by ochafik** [comment]
Hi @yang,

JNAerator now generates bindings for BridJ by default (you can ask for JNA bindings with `-runtime JNAerator`, which uses an extended JNA runtime with more capabilities, or `-runtime JNA`, which uses raw JNA).
To use BridJ bindings, java native methods need to be bound to their native counterparts. This is done by `BridJ.register(Python26Library.class)` (or by the static initializer that JNAerator should have inserted in generated classes).
I'll try to update the doc asap to reflect this behaviour :-)

Cheers

**Comment by ochafik** [comment]
_From @twitwi on December 16, 2011 10:20_

Hi,

I can add some things that I needed when I tried to wrap python.
* BridJ.addNativeLibraryAlias("python26", "python2.6");
* ^ I needed this because the library name contains a "." and at some point it got removed
* export LD_PRELOAD=/usr/lib/libpython2.6.so
* ^ (linux) before running the program, I need to use that or I get some problems when python tries to load some extensions

Rémi

**Comment by ochafik** [comment]
_From @yang on January 24, 2012 3:54_

Thanks for the tips.  The native library alias tip solved that problem.  I'm now encountering:

```
scala> Python26Library.Py_Initialize()
Jan 23, 2012 7:48:20 PM org.bridj.AbstractBridJRuntime log
SEVERE: Failed to get address of method public static native int python26.Python26Library.PyBuffer_SizeFromFormat(org.bridj.Pointer)
```

There also appear to be a bunch of missing methods, such as `PyRun_SimpleString`.  Not sure how to debug this....

**Comment by ochafik** [comment]
_From @twitwi on January 24, 2012 22:58_

Hi,

For the PyRun_SimpleString, it is actually a #define and I don't know if something should be generated and whether it is a parsing error. Olivier must know that :)
   include26/pythonrun.h:90:#define PyRun_SimpleString(s) PyRun_SimpleStringFlags(s, NULL)


I get the same error as you. Both scala and java exhibit it.
However it is not fatal and so a simple workaround is to ignore it.

Rémi

In the scala REPL:
  org.bridj.BridJ.addNativeLibraryAlias("python26", "python2.6");
  com.heeere.python26.Python26Library.Py_Initialize();
  com.heeere.python26.Python26Library.PyRun_SimpleStringFlags(org.bridj.Pointer.pointerToCString("print(40+2)"), null)

Or in Java:
import static com.heeere.python26.Python26Library.*;
import org.bridj.Pointer;

public class Test {
    public static Pointer<Byte> s(String string) {
        return Pointer.pointerToCString(string);
    }
    public static void main(String[] args) {
        org.bridj.BridJ.addNativeLibraryAlias("python26", "python2.6");
        com.heeere.python26.Python26Library.Py_Initialize();
        PyRun_SimpleStringFlags(s("print(41)"), null);
        PyRun_SimpleStringFlags(s("aa = 11\nprint(aa*2)"), null);
        PyRun_SimpleStringFlags(s("print(aa*3)"), null);
        PyRun_SimpleStringFlags(s("complexResult = {'a': 12, 'b': \"hi\"}"), null);
        PyRun_SimpleStringFlags(s("def fu(n):\n return n*n"), null);
    }
}

**Comment by ochafik** [comment]
_From @yang on January 25, 2012 0:9_

Ah, thanks @twitwi - didn't realize that was a macro. Still, there seem to be many actual symbols that aren't showing up:

```
$ java -jar jnaerator-0.9.9-SNAPSHOT-shaded.jar -library python26 /usr/include/python2.6/*.h -o dst -noJar -noComp -I /usr/lib/gcc/x86_64-linux-gnu/4.4/include/ 
/usr/include/python2.6/ImPlatform.h:13:20: error: #error Sorry, this library requires support for ANSI prototypes.
/usr/include/python2.6/ImPlatform.h:13:88: error: #error Sorry, this library requires ANSI header files.
/usr/include/python2.6/ImPlatform.h:29:89: error: #error Cannot find required 32-bit integer type
/usr/include/python2.6/pymactoolbox.h:6:0: error: File not found: Carbon/Carbon.h in /usr/lib/gcc/x86_64-linux-gnu/4.4/include . /usr/include /usr/include/c++/4.4.3
/usr/include/python2.6/pymactoolbox.h:8:0: error: File not found: QuickTime/QuickTime.h in /usr/lib/gcc/x86_64-linux-gnu/4.4/include . /usr/include /usr/include/c++/4.4.3
/usr/include/bits/wchar.h:30:7: warning: Unexpected nonwhite token
/usr/include/bits/wchar.h:30:7: warning: Unexpected nonwhite token
/usr/include/bits/wchar.h:30:7: warning: Unexpected nonwhite token
/usr/include/bits/wchar.h:30:7: warning: Unexpected nonwhite token
JNAeration completed !
/home/yang/tmp/dst

$ fgrep -r PyDict_New dst/python26/

$ fgrep -r PyEval_GetGlobals dst/python26/

$ fgrep -r PyDict_New /usr/include/python2.6
/usr/include/python2.6/dictobject.h:PyAPI_FUNC(PyObject *) PyDict_New(void);
/usr/include/python2.6/dictobject.h:PyAPI_FUNC(PyObject *) _PyDict_NewPresized(Py_ssize_t minused);

$ fgrep -r PyEval_GetGlobals /usr/include/python2.6
/usr/include/python2.6/ceval.h:PyAPI_FUNC(PyObject *) PyEval_GetGlobals(void);
```

**Comment by ochafik** [comment]
Hi @yang,

From looking at the python headers, you can get past the first errors by defining the following two macros in command line :
-DHAVE_PROTOTYPES= -DSTDC_HEADERS=

Cheers

**Comment by ochafik** [comment]
_From @yang on January 25, 2012 2:32_

The first two macros are straightforward, but there are many more of these checks, they're easy to get wrong, they're arch/machine-specific (e.g. SIZEOF_*), and they're tedious.

I'm currently going down the route of using `gcc -E` plus a bunch of scripts to munge that output to remove things jnaerator can't parse (such as source line number directives and annotations like `__attribute__` or `__asm__`) and to scope the definitions down to just the symbols/files I care about, but please let me know if there's a better avenue of attack.  Thanks.

**Comment by ochafik** [comment]
_From @yang on January 25, 2012 3:58_

OK, after actually making a bunch of progress here, am realizing this route isn't as foolproof as I thought since it loses `#define` information, which it turns out jnaerator *does* parse, e.g. `#define Py_eval_input 258`.  Is this the only form of `#define` I should throw in?  That actually doesn't seem too hard, but I feel I'm missing something obvious here.

**Comment by ochafik** [comment]
_From @yang on January 25, 2012 20:28_

I thought I'd try a different avenue of attack: simply dumping all the pre-defined macros from gcc with `gcc -dM -E - < /dev/null > macros` and prepending this include with:

```
java -jar jnaerator-0.9.9-SNAPSHOT-shaded.jar -library python26 -I macros /usr/include/python2.6/Python.h -o dst -I /usr/lib/gcc/x86_64-linux-gnu/4.4/include/ -noComp -noJar
```

But I'm still seeing the following errors:

```
/usr/include/python2.6/Python.h:16:14: error: #error "Something's broken.  UCHAR_MAX should be defined in limits.h."
/usr/include/python2.6/Python.h:18:14: error: #error "Python's source code assumes C's unsigned char is an 8-bit type."
/usr/include/bits/wchar.h:30:7: warning: Unexpected nonwhite token
/usr/include/bits/wchar.h:30:7: warning: Unexpected nonwhite token
/usr/include/bits/wchar.h:30:7: warning: Unexpected nonwhite token
/usr/include/bits/wchar.h:30:7: warning: Unexpected nonwhite token
JNAeration completed !
/home/yang/tmp/dst
```

(and the resulting Python26Library.java is barely filled out)
