### ISSUE TITLE
NullPointerException in JNAeratorParser

### ISSUE THREAD

**Issue by ochafik** [ochafik/JNAerator#43]
_From @blair0011 on February 25, 2013 22:13_

I am trying to generate wrapper classes via JNAerator but I either do not get anything generated or this error happens (I added -parseChunks after reading another issue entry). Oh I am running on CentOS 6.3 with Oracle JDK 1.7.0_10b18.

java -jar jnaerator-0.11-shaded.jar config.jnaerator libA.h
Auto-configuring parser...
Feb 25, 2013 1:48:30 PM com.ochafik.lang.jnaerator.JNAeratorConfigUtils getProp
INFO: [environment] JNAERATOR_INCLUDE_PATH=.:/usr/include:/usr/local/include:/usr/include/c++/4.4.6:/usr/include/c++/4.4.6/tr1
Feb 25, 2013 1:48:30 PM com.ochafik.lang.jnaerator.JNAeratorConfigUtils getProp
INFO: [environment] JNAERATOR_FRAMEWORKS_PATH=/System/Library/Frameworks/CoreServices.framework/Versions/Current/Frameworks:/System/Library/Frameworks/ApplicationServices.framework/Versions/Current/Frameworks:/System/Library/Frameworks:/Library/Frameworks:/Local/Library/Frameworks/:/home/blair/Library/Frameworks
os.arch = amd64
Feb 25, 2013 1:48:30 PM com.ochafik.lang.jnaerator.JNAerator jnaerate
INFO: Include path : 
	/usr/include/c++/4.4.6/x86_64-redhat-linux
	/usr/lib/gcc/x86_64-redhat-linux/4.4.6/include
	.
	/usr/include
	/usr/local/include
	/usr/include/c++/4.4.6
	/usr/include/c++/4.4.6/tr1
Parsing native headers...
Writing preprocessor output to '_jnaerator.preprocessed.c'
Writing preprocessor macros to '_jnaerator.macros.cpp'
Now trying to parse sources slice by slice.
Now parsing 418 slices
java.util.concurrent.ExecutionException: com.ochafik.lang.jnaerator.JNAeratorParser$ParseError: Failed to parse because of java.lang.NullPointerException
	at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:262)
	at java.util.concurrent.FutureTask.get(FutureTask.java:119)
	at com.ochafik.lang.jnaerator.JNAeratorParser.parse(JNAeratorParser.java:267)
	at com.ochafik.lang.jnaerator.JNAerator.parseSources(JNAerator.java:1224)
	at com.ochafik.lang.jnaerator.JNAerator.jnaerate(JNAerator.java:923)
	at com.ochafik.lang.jnaerator.JNAerator$1.finished(JNAerator.java:734)
	at com.ochafik.lang.jnaerator.JNAeratorCommandLineArgs$ArgsParser.parse(JNAeratorCommandLineArgs.java:135)
	at com.ochafik.lang.jnaerator.JNAerator.main(JNAerator.java:239)
	at com.ochafik.lang.jnaerator.JNAerator.main(JNAerator.java:212)
Caused by: com.ochafik.lang.jnaerator.JNAeratorParser$ParseError: Failed to parse because of java.lang.NullPointerException
	at com.ochafik.lang.jnaerator.JNAeratorParser$1.call(JNAeratorParser.java:160)
	at com.ochafik.lang.jnaerator.JNAeratorParser$1.call(JNAeratorParser.java:126)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.NullPointerException
	at com.ochafik.lang.jnaerator.parser.ObjCppParser.qualifiedCppFunctionName(ObjCppParser.java:9697)
	at com.ochafik.lang.jnaerator.parser.ObjCppParser.functionDeclaration(ObjCppParser.java:4417)
	at com.ochafik.lang.jnaerator.parser.ObjCppParser.declaration(ObjCppParser.java:1153)
	at com.ochafik.lang.jnaerator.parser.ObjCppParser.namespaceDecl(ObjCppParser.java:1421)
	at com.ochafik.lang.jnaerator.parser.ObjCppParser.declaration(ObjCppParser.java:1274)
	at com.ochafik.lang.jnaerator.parser.ObjCppParser.sourceFile(ObjCppParser.java:763)
	at com.ochafik.lang.jnaerator.JNAeratorParser$1.call(JNAeratorParser.java:140)
	... 6 more
Parsing failed : java.util.concurrent.ExecutionException: com.ochafik.lang.jnaerator.JNAeratorParser$ParseError: Failed to parse because of java.lang.NullPointerException
Parsing failed : java.util.concurrent.TimeoutException
Parsing failed : java.util.concurrent.TimeoutException

My config file is this:
-library my_bridj
-I /usr/include/c++/4.4.6/x86_64-redhat-linux
-I /usr/lib/gcc/x86_64-redhat-linux/4.4.6/include/
-mode StandaloneJar 
-reification 
-package libACE 
-v 
-f
-parseChunks

_Copied from original issue: ochafik/nativelibs4java#380_

**Comment by ochafik** [comment]
Hi @blair0011 ,

Thanks for your report!
Will investigate asap...

Cheers

**Comment by ochafik** [comment]
_From @sk- on June 11, 2014 8:56_

I'm having the same problem. the problem seems to be the `#include <vector>`.
