### ISSUE TITLE
Parsing arguments: java.lang.IndexOutOfBoundsException: Index: 15, Size: 15

### ISSUE THREAD

**Issue by ochafik** [ochafik/JNAerator#80]
_From @shevek on December 24, 2014 23:7_

       Error parsing arguments :
```
       -library parted -package org.anarres.device.parted.generated /usr/include/parted/parted.h -mode Directory -runtime JNA -o /home/shevek/java/udev4j/parted/build/generated-sources/jnaerator -f -v(?:erbose)? -Dtime_t=long -D_STDIO_H : java.lang.IndexOutOfBoundsException: Index: 15, Size: 15
```

```
Caused by: java.lang.IndexOutOfBoundsException: Index: 15, Size: 15
        at java.util.ArrayList.rangeCheck(ArrayList.java:635)
        at java.util.ArrayList.get(ArrayList.java:411)
        at com.ochafik.lang.jnaerator.JNAeratorCommandLineArgs$ArgsParser.parse(JNAeratorCommandLineArgs.java:122)
```

0.12-SNAPSHOT

Please consider using JOptSimple, it's very good indeed and appears to be the standard now.

_Copied from original issue: ochafik/nativelibs4java#545_

**Comment by ochafik** [comment]
_From @shevek on December 24, 2014 23:10_

Appears to be caused by the -D_STDIO_H in an attempt to workaround another bug.

**Comment by ochafik** [comment]
_From @shevek on December 24, 2014 23:25_

Caused by not having an = sign.

Note that -D<space>_STDIO_H causes really WEIRD behaviour.
